// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface New {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  published_on: string;
  summary?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  audience?: "all" | "young-people" | "parents-carers" | "schools" | "social-workers" | "professionals";
  featured_on_homepage?: boolean;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Event {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  kind?: "training" | "event" | "network";
  starts_at: string;
  ends_at?: string;
  location?: string;
  is_online?: boolean;
  booking_url?: string;
  audience?: "all" | "young-people" | "parents-carers" | "schools" | "social-workers" | "professionals";
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Document {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  category?: "policy" | "guidance" | "form" | "report" | "other";
  audience?: "all" | "young-people" | "parents-carers" | "schools" | "social-workers" | "professionals";
  file?: { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };
  external_url?: string;
  doc_version?: string;
  updated_on?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface TeamMember {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  role: string;
  remit?: string;
  email?: string;
  phone?: string;
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer?: PortableTextBlock[];
  audience?: "all" | "young-people" | "parents-carers" | "schools" | "social-workers" | "professionals";
  order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Outcome {
  id: string;
  slug: string | null;
  status: string;
  academic_year: string;
  metric: "attendance" | "persistent-absence" | "fixed-term-exclusions" | "progress-reading" | "progress-maths" | "ppp-spend" | "care-leavers-in-education";
  value: string;
  comparison?: string;
  note?: string;
  order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    news: New;
    events: Event;
    documents: Document;
    team_members: TeamMember;
    faqs: Faq;
    outcomes: Outcome;
  }
}